[package]
name = "leptos-query"
version = "0.1.0"
edition = "2021"
authors = ["Nico Burniske"]
description = "Async resource manager for Leptos"
exclude = ["example/"]
keywords = ["leptos"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/nicoburniske/leptos-query"

[dependencies]
leptos = "0.4"
cfg-if = "1"
js-sys = {version = "0.3.64", optional = true}

[features]
hydrate = ["dep:js-sys"] 
